# Generated by Django 4.2 on 2023-06-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.IntegerField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=30)),
                ('Plant', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
            ],
        ),
    ]
